version: 1.0.{build}
pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true
environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
build_script:
- ps: .\build.ps1
test: off
artifacts:
# Store NuGet packages
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
# Publish NuGet packages
- provider: NuGet
  name: production
  api_key:
    secure: 73eFUWSfho6pxCy1VRP1H0AYh/SFiyEREV+/ATcoj0I+sSH9dec/WXs6H2Jy5vlS
  on:
    # Only publish from the master branch
    branch: master
    # Only publish if the trigger was a Git tag
    # git tag v0.1.0-beta
    # git push origin --tags
    appveyor_repo_tag: true